<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE suzuki [


<!ELEMENT suzuki     (manual+) >
<!ATTLIST suzuki     booktype  CDATA     #IMPLIED
                     dataspec  CDATA     #IMPLIED >

<!ELEMENT paragroup  (title?, (figure | torque | spec | spec-sdm | sd2 |
                              materials | servicetool | attention1 |
                              attention2 | attention3 | attention4 | ptxt |
                              p-change | c-change)+) >

<!ELEMENT ptxt       (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol | button)* >

<!ELEMENT list1      (title?, figure*, symbol*, item, ((symbol*, item) |
                              list2 | p-change | c-change)*) >
<!ATTLIST list1      type      (ordered|unordered)  #REQUIRED >

<!ELEMENT figure     ((title)?, (graphic), (callout | callout-l |
                              p-change | c-change)?) >
<!ATTLIST figure     figuretype  CDATA     #IMPLIED
                     page      (1|2)     #IMPLIED >

<!ELEMENT graphic    EMPTY >
<!ATTLIST graphic    ver       CDATA     #IMPLIED
                     gh        CDATA     #IMPLIED
                     gw        CDATA     #IMPLIED
                     turn      (on|off)  #IMPLIED
                     entity    ENTITY    #IMPLIED
                     file      CDATA     #IMPLIED
                     dpi       NMTOKEN   #IMPLIED
                     rasterdpi  NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     width     CDATA     #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED
                     insetdata  CDATA     #IMPLIED
                     posterfile  CDATA     #IMPLIED
                     graphicname  CDATA     #IMPLIED
                     javascriptfile  CDATA     #IMPLIED
                     activateinpdf  NMTOKEN   #IMPLIED
                     openpopupwin  NMTOKEN   #IMPLIED
                     insetview  CDATA     #IMPLIED
                     bgcolor   NMTOKEN   #IMPLIED
                     rendermode  NMTOKEN   #IMPLIED
                     lighting  NMTOKEN   #IMPLIED
                     linktotext  CDATA     #IMPLIED >

<!ELEMENT table      (title?, (paragroup | ptxt | attention1 | attention2
                              | attention3 | attention4 | p-change |
                              c-change)*, (tgroup, (p-change | c-change)?)+) >
<!ATTLIST table      frame     (all|none|top|bottom|topbot|sides)  #IMPLIED
                     pgwide    CDATA     #IMPLIED
                     page      (1|2)     #IMPLIED
                     tabletype  (material|tool|general|2rin0A|Torque|ServiceDataList)  #IMPLIED >

<!ELEMENT diag       ((testgroup, (p-change | c-change)?)+ | (condition,
                              (ps, action)+)+) >
<!ATTLIST diag       type      (test|condition)  #REQUIRED
                     id        ID        #IMPLIED >

<!ELEMENT action     (paragroup | ptxt | list1)+ >

<!ELEMENT title      (#PCDATA | emph | intxreftitleoff | intxreftitleoff1
                              | intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT p-change   EMPTY >
<!ATTLIST p-change   enable    (true|false)  #IMPLIED >

<!ELEMENT c-change   EMPTY >
<!ATTLIST c-change   enable    (true|false)  #IMPLIED >

<!ELEMENT attention1 (title?, (paragroup | ptxt | list1 | figure | table
                              | p-change | c-change)+) >

<!ELEMENT attention2 (title?, (paragroup | ptxt | list1 | figure | table
                              | p-change | c-change)+) >

<!ELEMENT attention3 (title?, (paragroup | ptxt | list1 | figure | table
                              | p-change | c-change)+) >

<!ELEMENT attention4 (title?, (paragroup | ptxt | list1 | figure | table
                              | p-change | c-change)+) >

<!ELEMENT infoid     EMPTY >

<!ELEMENT button     EMPTY >
<!ATTLIST button     type      (activetest|dtcclear|dtccheck|utility)  #REQUIRED
                     code      CDATA     #REQUIRED >

<!ELEMENT tgroup     (thead?, tbody) >
<!ATTLIST tgroup     align     (left|right|center)  #IMPLIED >

<!ELEMENT callout    (table) >

<!ELEMENT callout-l  (table) >

<!ELEMENT test1      ((torque | spec | spec-sdm | sd2 | materials |
                              servicetool | paragroup | ptxt | testfigure |
                              list1 | p-change | c-change)+, (test2, (p-change
                              | c-change)*)*) >

<!ELEMENT torque     (torqueitem, (p-change | c-change)?)+ >

<!ELEMENT spec       (title, (paragroup | ptxt | figure | table | list1 |
                              p-change | c-change)+) >

<!ELEMENT spec-sdm   (sdm-title, sdm-part?, sdm-model?, sdm1+) >
<!ATTLIST spec-sdm   sdmid     ID        #IMPLIED >

<!ELEMENT sd2        (sd2-title, sd2-1+) >
<!ATTLIST sd2        display   (on|off)  #IMPLIED
                     sectionid  CDATA     #IMPLIED >

<!ELEMENT materials  (materialitem, (p-change | c-change)?)+ >

<!ELEMENT servicetool 
                     (servicetoolitem, (p-change | c-change)?)+ >

<!ELEMENT condition  (test1 | torque | spec | spec-sdm | sd2 | materials
                              | servicetool | attention1 | attention2 |
                              attention3 | attention4 | paragroup | ptxt |
                              figure)+ >

<!ELEMENT typename   (#PCDATA) >

<!ELEMENT servinfotype 
                     (sitname, ((symptom | symptomoff | servinfo),
                              (p-change | c-change)?)+) >
<!ATTLIST servinfotype 
                     sitcode   (0|1|2|3|4|5|6|7|8|A|B|C|D|E|F|G|H|S|T)  #REQUIRED
                     sitname   CDATA     #IMPLIED >

<!ELEMENT configtype (typename?, (servinfotype, (p-change | c-change)?)+)>
<!ATTLIST configtype 
                     typenbr   CDATA     #REQUIRED
                     typename  CDATA     #IMPLIED >

<!ELEMENT def        (paragroup | ptxt | figure | table | list1 | torque
                              | spec | spec-sdm | sd2 | materials |
                              servicetool | attention1 | attention2 |
                              attention3 | attention4 | p-change | c-change)+ >

<!ELEMENT term       (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >
<!ATTLIST term       id        ID        #IMPLIED >

<!ELEMENT deflist    (term, def, (p-change | c-change)?)+ >

<!ELEMENT testgroup  (title?, (s1 | paragroup | ptxt | list1 | diag |
                              testfigure | deflist | torque | spec | spec-sdm
                              | sd2 | materials | servicetool | p-change |
                              c-change)*, (test1, (p-change | c-change)*)*,
                              question, (testfigure | p-change | c-change)*,
                              (result, action)+) >
<!ATTLIST testgroup  id        ID        #IMPLIED >

<!ELEMENT ps         (paragroup | ptxt)+ >

<!ELEMENT servinfo   (title, infoid?, subtitle*, ((servinfosub |
                              scantool) | (s1 | paragroup | ptxt | list1 |
                              table | diag | figure | deflist | torque | spec
                              | spec-sdm | sd2 | materials | servicetool |
                              attention1 | attention2 | attention3 |
                              attention4 | p-change | c-change))+) >
<!ATTLIST servinfo   servinfosgmlid  ID        #REQUIRED
                     svcinfotypenbr  CDATA     #REQUIRED
                     svcinfoqualnbr  CDATA     #REQUIRED
                     originsieid  CDATA     #IMPLIED
                     page      (1|2)     #IMPLIED
                     systemcode  CDATA     #IMPLIED
                     releasenbr  (1|2)     #IMPLIED
                     poff      (1|2)     #IMPLIED
                     supplyoff  (0|1)     #IMPLIED
                     modify    CDATA     #IMPLIED >

<!ELEMENT documentmodules 
                     ((materials | servicetool | torque | servinfo |
                              graphic)*) >

<!ELEMENT dummypgf   EMPTY >

<!ELEMENT sub        (#PCDATA) >

<!ELEMENT sup        (#PCDATA) >

<!ELEMENT intxref    EMPTY >
<!ATTLIST intxref    refid     IDREF     #REQUIRED
                     format    CDATA     #IMPLIED
                     srcfile   CDATA     #IMPLIED >

<!ELEMENT intxrefsupplyoff 
                     (#PCDATA) >
<!ATTLIST intxrefsupplyoff 
                     refid     CDATA     #REQUIRED
                     label     CDATA     #IMPLIED >

<!ELEMENT intxrefpoff 
                     EMPTY >
<!ATTLIST intxrefpoff 
                     refid     IDREF     #REQUIRED
                     format    CDATA     #IMPLIED
                     srcfile   CDATA     #IMPLIED >

<!ELEMENT extxref    EMPTY >
<!ATTLIST extxref    label1    CDATA     #IMPLIED
                     label2    CDATA     #IMPLIED
                     oldid     CDATA     #IMPLIED
                     oldtype   (intxref|intxreftitleoff|intxreftitleoff1|intxrefpoff)  #REQUIRED >

<!ELEMENT uxref      EMPTY >
<!ATTLIST uxref      label1    CDATA     #IMPLIED
                     label2    CDATA     #IMPLIED
                     oldid     CDATA     #IMPLIED
                     oldtype   (intxref|intxreftitleoff|intxreftitleoff1|intxrefpoff)  #IMPLIED >

<!ELEMENT intxreftitleoff 
                     EMPTY >
<!ATTLIST intxreftitleoff 
                     refid     IDREF     #REQUIRED
                     format    CDATA     #IMPLIED
                     srcfile   CDATA     #IMPLIED >

<!ELEMENT intxreftitleoff1 
                     EMPTY >
<!ATTLIST intxreftitleoff1 
                     refid     IDREF     #REQUIRED
                     format    CDATA     #IMPLIED
                     srcfile   CDATA     #IMPLIED >

<!ELEMENT intxreftitleoffsupplyoff 
                     EMPTY >
<!ATTLIST intxreftitleoffsupplyoff 
                     refid     CDATA     #REQUIRED
                     titleoff  CDATA     "0" >

<!ELEMENT symbol     EMPTY >
<!ATTLIST symbol     entity    ENTITY    #IMPLIED
                     file      CDATA     #IMPLIED
                     dpi       NMTOKEN   #IMPLIED
                     rasterdpi  NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     width     CDATA     #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED
                     insetdata  CDATA     #IMPLIED
                     posterfile  CDATA     #IMPLIED
                     graphicname  CDATA     #IMPLIED
                     javascriptfile  CDATA     #IMPLIED
                     activateinpdf  NMTOKEN   #IMPLIED
                     openpopupwin  NMTOKEN   #IMPLIED
                     insetview  CDATA     #IMPLIED
                     bgcolor   NMTOKEN   #IMPLIED
                     rendermode  NMTOKEN   #IMPLIED
                     lighting  NMTOKEN   #IMPLIED
                     linktotext  CDATA     #IMPLIED >

<!ELEMENT emph       (#PCDATA | sub | sup | intxref | intxrefsupplyoff |
                              intxrefpoff | extxref | uxref | intxreftitleoff
                              | intxreftitleoff1 | intxreftitleoffsupplyoff |
                              symbol)* >
<!ATTLIST emph       etype     (bold|ital|roman)  #IMPLIED >

<!ELEMENT graphic-dummy 
                     EMPTY >
<!ATTLIST graphic-dummy 
                     entity    ENTITY    #IMPLIED
                     file      CDATA     #IMPLIED
                     dpi       NMTOKEN   #IMPLIED
                     rasterdpi  NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     width     CDATA     #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED
                     insetdata  CDATA     #IMPLIED
                     posterfile  CDATA     #IMPLIED
                     graphicname  CDATA     #IMPLIED
                     javascriptfile  CDATA     #IMPLIED
                     activateinpdf  NMTOKEN   #IMPLIED
                     openpopupwin  NMTOKEN   #IMPLIED
                     insetview  CDATA     #IMPLIED
                     bgcolor   NMTOKEN   #IMPLIED
                     rendermode  NMTOKEN   #IMPLIED
                     lighting  NMTOKEN   #IMPLIED
                     linktotext  CDATA     #IMPLIED >

<!ELEMENT entry      ((dummypgf?, (graphic | graphic-dummy), ptxt*) |
                              (title?, (paragroup | ptxt | deflist | list1 |
                              attention1 | attention2 | attention3 |
                              attention4)*)) >
<!ATTLIST entry      valign    (top|middle|bottom)  #IMPLIED
                     align     (left|right|center)  #IMPLIED
                     border-top  CDATA     #IMPLIED
                     border-bottom  CDATA     #IMPLIED
                     border-left  CDATA     #IMPLIED
                     border-right  CDATA     #IMPLIED >

<!ELEMENT testfigure (title?, graphic) >

<!ELEMENT list2      (title?, figure*, symbol*, item, ((symbol*, item) |
                              list3 | p-change | c-change)*) >
<!ATTLIST list2      type      (ordered|unordered)  #REQUIRED >

<!ELEMENT list3      (title?, figure*, symbol*, item, (symbol*, (item |
                              p-change | c-change))*) >
<!ATTLIST list3      type      (ordered|unordered)  #REQUIRED >

<!ELEMENT item       (ptxt, (paragroup | ptxt | figure | testfigure |
                              deflist | table | torque | spec | spec-sdm | sd2
                              | materials | servicetool | attention1 |
                              attention2 | attention3 | attention4 | p-change
                              | c-change)*) >

<!ELEMENT limit-off  (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT limit-on   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT m-name     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT m-number   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT m-desc     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT m-part     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT m-type     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT section    (servcat+) >
<!ATTLIST section    sectnbr   CDATA     #REQUIRED >

<!ELEMENT manual     (section+) >
<!ATTLIST manual     type      CDATA     #IMPLIED
                     manualid  CDATA     #IMPLIED
                     manualname  CDATA     #IMPLIED
                     lang      CDATA     #IMPLIED >

<!ELEMENT materialitem 
                     (m-part?, (m-type | m-desc)?, m-number?, m-name?,
                              ptxt?) >
<!ATTLIST materialitem 
                     name      CDATA     #IMPLIED
                     id        ID        #IMPLIED
                     uid       CDATA     #IMPLIED >

<!ELEMENT poff       (title, (ptxt)+) >

<!ELEMENT sdm1       (sdm-condition, ((sdm-value, ptxt?, sdm-ptxt?) |
                              sdm2+)) >

<!ELEMENT sdm2       (sdm-condition, sdm-value, ptxt?, sdm-ptxt?) >

<!ELEMENT sdm-ptxt   (#PCDATA)* >

<!ELEMENT question   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT result     EMPTY >
<!ATTLIST result     type      (yes|no)  #IMPLIED >

<!ELEMENT row        (entry+) >

<!ELEMENT s-name     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >
<!ATTLIST s-name     num       CDATA     #IMPLIED >

<!ELEMENT s-number   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >
<!ATTLIST s-number   num       CDATA     #IMPLIED >

<!ELEMENT s-part     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT s2         (ptxt, (paragroup | ptxt | list1 | torque | spec |
                              spec-sdm | sd2 | materials | servicetool |
                              figure | deflist | table | attention1 |
                              attention2 | attention3 | attention4 | s3 |
                              p-change | c-change)*) >

<!ELEMENT servinfosub 
                     (title, poff?, subtitle*, (s1 | paragroup | ptxt |
                              list1 | table | diag | figure | deflist | torque
                              | spec | spec-sdm | sd2 | materials |
                              servicetool | attention1 | attention2 |
                              attention3 | attention4 | topic | p-change |
                              c-change)+) >
<!ATTLIST servinfosub 
                     id        ID        #IMPLIED
                     page      (1|2)     #IMPLIED
                     supplyoff  (0|1)     #IMPLIED >

<!ELEMENT scantool   (scantool-title, poff?, ((servinfosub) | (s1 |
                              paragroup | ptxt | list1 | table | diag | figure
                              | deflist | torque | spec | spec-sdm | sd2 |
                              materials | servicetool | attention1 |
                              attention2 | attention3 | attention4 | p-change
                              | c-change))+) >
<!ATTLIST scantool   id        ID        #IMPLIED
                     supplyoff  (0|1)     #IMPLIED
                     page      (1|2)     #IMPLIED >

<!ELEMENT topic      (title, poff?, subtitle*, (s1 | paragroup | ptxt |
                              list1 | table | diag | figure | deflist | torque
                              | spec | spec-sdm | sd2 | materials |
                              servicetool | attention1 | attention2 |
                              attention3 | attention4 | subtopic | p-change |
                              c-change)+) >
<!ATTLIST topic      id        ID        #IMPLIED
                     page      (1|2)     #IMPLIED
                     supplyoff  (0|1)     #IMPLIED >

<!ELEMENT subtopic   (title, poff?, subtitle*, (s1 | paragroup | ptxt |
                              list1 | table | diag | figure | deflist | torque
                              | spec | spec-sdm | sd2 | materials |
                              servicetool | attention1 | attention2 |
                              attention3 | attention4 | p-change | c-change)+)>
<!ATTLIST subtopic   id        ID        #IMPLIED
                     page      (1|2)     #IMPLIED
                     supplyoff  (0|1)     #IMPLIED >

<!ELEMENT s1         (ptxt, (paragroup | ptxt | list1 | torque | spec |
                              spec-sdm | sd2 | materials | servicetool |
                              figure | deflist | table | attention1 |
                              attention2 | attention3 | attention4 | s2 |
                              p-change | c-change)*) >
<!ATTLIST s1         page      (1|2)     #IMPLIED >

<!ELEMENT s3         (ptxt, (paragroup | ptxt | list1 | torque | spec |
                              spec-sdm | sd2 | materials | servicetool |
                              figure | deflist | table | attention1 |
                              attention2 | attention3 | attention4 | p-change
                              | c-change)*) >

<!ELEMENT scantool-title 
                     (#PCDATA) >

<!ELEMENT scname     (#PCDATA) >

<!ELEMENT sctname    (#PCDATA) >

<!ELEMENT sd2-title  (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sd2-1      (sd2-condition, ((sd2-break?, (standard-on |
                              standard-off)?, (limit-on | limit-off)?) |
                              sd2-2*)) >

<!ELEMENT sd2-condition 
                     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sd2-break  EMPTY >

<!ELEMENT standard-on 
                     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT standard-off 
                     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sd2-2      (sd2-condition, sd2-break?, (standard-on |
                              standard-off)?, (limit-on | limit-off)?) >

<!ELEMENT sdm-value  (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sdm-condition 
                     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sdm-model  (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sdm-part   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT sdm-title  (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT servcat    (sctname, scname, (configtype, (p-change |
                              c-change)?)+) >
<!ATTLIST servcat    sctnbr    CDATA     #REQUIRED
                     scnbr     CDATA     #REQUIRED
                     sctname   CDATA     #IMPLIED >

<!ELEMENT servicetoolitem 
                     (s-part?, s-number, s-name?, ptxt?) >
<!ATTLIST servicetoolitem 
                     id        ID        #IMPLIED >

<!ELEMENT subtitle   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT symptom    (servinfo, (p-change | c-change)?)+ >
<!ATTLIST symptom    sympsgmlid  ID        #REQUIRED
                     sympcatgnbr  CDATA     #REQUIRED
                     sympdesc  CDATA     #REQUIRED
                     sympcode  CDATA     #IMPLIED >

<!ELEMENT sitname    (#PCDATA) >

<!ELEMENT symptomoff (servinfo, (p-change | c-change)?)+ >
<!ATTLIST symptomoff 
                     sympsgmlid  ID        #REQUIRED
                     sympcatgnbr  CDATA     #REQUIRED
                     sympdesc  CDATA     #REQUIRED
                     sympcode  CDATA     #IMPLIED >

<!ELEMENT t-note     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT t-part1    (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT t-part     (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT t-value1   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT t-value3   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT t-value2   (#PCDATA | emph | sub | sup | intxref |
                              intxrefsupplyoff | intxrefpoff | extxref | uxref
                              | intxreftitleoff | intxreftitleoff1 |
                              intxreftitleoffsupplyoff | symbol)* >

<!ELEMENT tbody      (row+) >
<!ATTLIST tbody      valign    (top|middle|bottom)  #IMPLIED >

<!ELEMENT test2      ((torque | spec | spec-sdm | sd2 | materials |
                              servicetool | paragroup | ptxt | testfigure |
                              list1 | p-change | c-change)+, (test3, (p-change
                              | c-change)*)*) >

<!ELEMENT test3      (torque | spec | spec-sdm | sd2 | materials |
                              servicetool | paragroup | ptxt | testfigure |